version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
      - ./next-app/prisma:/app/prisma
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - rush_network

  db:
    build:
      context: ./db
    container_name: postgres
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - rush_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  rush_network:
    external: true
