version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: postgres-postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      GEOJSON_DIR: ${GEOJSON_DIR}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./web
    container_name: next-app
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
        NODE_ENV: development
        WDS_SOCKET_HOST: 127.0.0.1
        CHOKIDAR_USEPOLLING: true
        WATCHPACK_POLLING: true
        DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    depends_on:
      - db

volumes:
  pgdata:
